annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 10.6.12
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: MariaDB is an open source, community-developed SQL database server that
  is widely in use around the world due to its enterprise features, flexibility, and
  collaboration with leading tech firms.
name: mariadb
version: 11.4.7
